#!/usr/bin/env bash

#	Automated Timestamping
#
#	Copyright (c) 2021 Johannes Milczewski
#
#	Permission is hereby granted, free of charge, to any person obtaining a copy
#	of this software and associated documentation files (the "Software"), to deal
#	in the Software without restriction, including without limitation the rights
#	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#	copies of the Software, and to permit persons to whom the Software is
#	furnished to do so, subject to the following conditions:
#
#	The above copyright notice and this permission notice shall be included in all
#	copies or substantial portions of the Software.
#
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#	SOFTWARE.

function hook_echo() {
	local TAG="pre-push"
	echo -e "[\e[0;32m${TAG}\e[0m]: $1"
}

function maybe_withhold() {
	if [ $# -lt 2 ]; then
		echo "$#"
		die 'Call this script only through "git push".'
	fi

	if [[ ${TS_PUSH_WITHHOLD} != "true" ]]; then
		return 0
	fi

	local _
	local LOCAL_OID
	while read -r _ LOCAL_OID _ _; do
		local BRANCHES
		BRANCHES=$(is_timestamping_only_object "${LOCAL_OID}")
		case $? in
		0)
			return 0
			;;
		1)
			hook_echo "ERROR: '${LOCAL_OID}' is part of timestamping branch ${BRANCHES}"
			return 1
			;;
		esac
	done

	return 0
}

function ts-pre-push() {
	# shellcheck source=timestamping.sh
	source "$(dirname "$(realpath "$0")")/timestamping.sh"

	if_enabled in_environment maybe_withhold "$@"
	return $?
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	ts-pre-push "$@"
	exit $?
fi
